### ISSUE TITLE
XML Vector Drawable Filenames

### ISSUE THREAD

**Issue by bkhall** [Pictogrammers/pictogrammers.com#28]
Typically, these drawables are used on the Android platform.

Please replace the "-" (dashes) in the target filename with "_" (underscores).

Dashes in resource filenames are not allowed, so we must manually change the downloaded filename as described before we can use them.

**Comment by mririgoyen** [comment]
Fixed in https://github.com/Pictogrammers/pictogrammers.com/commit/6ec9f4ab5414a0134f69c377e741b432492bce6c. It takes about 40m for the site to redeploy.

**Comment by mririgoyen** [comment]
Change is live! Thanks for the report.

**Comment by bkhall** [comment]
Confirmed! Thanks for the quick fix.

**Comment by bkhall** [comment]
Need to reopen this.

The filenames which have a descriptor appended still have the - (dash).

For example: play_circle-outline.xml

**Comment by mririgoyen** [comment]
Fixed again in https://github.com/Pictogrammers/pictogrammers.com/commit/2e9192f2b060f74725b8724010405c240e2f4c65. Sorry about that. Changes should be live in about an hour.

**Comment by bkhall** [comment]
Fix looks good. Thank you!
